version: '3.8'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm start"
    depends_on:
      - mongo
      # - postgres
    env_file:
      - .env

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Add vector for Betterstack logging
  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector-config:/etc/vector
      - ./vector-data:/var/lib/vector
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8686:8686'
    container_name: vector
    depends_on:
      - payload
      - mongo
      - redis
    restart: unless-stopped

volumes:
  data:
  # pgdata:
  node_modules:
  redis_data:
